- name: Provision EC2 Instances
  hosts: localhost
  roles:
    - terraform

- name: Configure Kubernetes Nodes
  hosts: all
  become: true
  roles:
    - k8s_setup

- name: Setup Kubernetes Cluster
  hosts: all
  become: true
  roles:
    - cluster_setup


